export const customerPricingCopy = {
  en: {
    title: 'Prices & discounts',
    open: 'Manage prices',
    summary: 'Review Tier, catalogue, and customer-specific net prices',
    back: 'Back to profile',
    add: 'Add net price',
    edit: 'Edit net price',
    readOnly: 'You can view approved prices. Only Owner/Admin can change them.',
    priority: 'A customer net price replaces the Tier price for this SKU and is not discounted twice.',
    tier: 'Current Tier',
    tierDiscount: 'Tier discount',
    activeRules: 'Active net prices',
    searchProduct: 'Search product by SKU or name',
    searchHint: 'Type at least 2 characters. Results are loaded only when you search.',
    reload: 'Reload',
    loading: 'Loading prices...',
    searching: 'Searching...',
    noProducts: 'No matching active product',
    product: 'Product',
    cataloguePrice: 'Catalogue price',
    basePrice: 'After normal discount',
    tierPrice: 'Tier price',
    netPrice: 'Customer net price',
    unit: 'Unit',
    currency: 'THB',
    validFrom: 'Starts',
    validUntil: 'Expires',
    noExpiry: 'No expiry',
    note: 'Note',
    notePlaceholder: 'Reason or agreed terms (optional)',
    save: 'Save price',
    saving: 'Saving...',
    cancel: 'Cancel',
    showExpired: 'Show expired prices',
    hideExpired: 'Hide expired prices',
    empty: 'No customer-specific net price yet',
    effectivePrice: 'Current system price',
    updated: 'Updated',
    statusActive: 'Active',
    statusScheduled: 'Scheduled',
    statusExpired: 'Expired',
    statusExpiredActive: 'Expired · deactivate rule',
    expire: 'Expire now',
    expireConfirm: 'Confirm expiry',
    expireQuestion: 'Disable this SKU rule and use Tier or catalogue pricing.',
    invalidProduct: 'Select a product first',
    invalidPrice: 'Net price must be greater than 0',
    invalidDates: 'Expiry must be later than the start time',
    duplicate: 'This SKU already has an active net-price rule. Deactivate it before adding another.',
    loadFailed: 'Unable to load prices',
    saveFailed: 'Unable to save price',
    expiredSaved: 'The net price has expired',
    saved: 'Price saved',
    priceBase: 'Catalogue price',
    priceTier: 'Tier price',
    priceNet: 'Customer net price',
    priceCalculated: 'Calculated price',
  },
  th: {
    title: 'ราคาและส่วนลด',
    open: 'จัดการราคา',
    summary: 'ดูราคา Tier ราคาปกติ และราคาเน็ตเฉพาะลูกค้า',
    back: 'กลับโปรไฟล์',
    add: 'เพิ่มราคาเน็ต',
    edit: 'แก้ราคาเน็ต',
    readOnly: 'ดูราคาที่อนุมัติแล้วได้ การแก้ราคาใช้สิทธิ์ Owner/Admin เท่านั้น',
    priority: 'ราคาเน็ตจะแทนราคา Tier เฉพาะ SKU นี้ และไม่ถูกหักส่วนลดซ้ำ',
    tier: 'Tier ปัจจุบัน',
    tierDiscount: 'ส่วนลด Tier',
    activeRules: 'ราคาเน็ตที่ใช้งาน',
    searchProduct: 'ค้นหาสินค้าด้วย SKU หรือชื่อ',
    searchHint: 'พิมพ์อย่างน้อย 2 ตัวอักษร ระบบจะโหลดเมื่อค้นหาเท่านั้น',
    reload: 'โหลดใหม่',
    loading: 'กำลังโหลดราคา...',
    searching: 'กำลังค้นหา...',
    noProducts: 'ไม่พบสินค้าที่เปิดใช้งาน',
    product: 'สินค้า',
    cataloguePrice: 'ราคาคลัง',
    basePrice: 'หลังส่วนลดปกติ',
    tierPrice: 'ราคา Tier',
    netPrice: 'ราคาเน็ตลูกค้า',
    unit: 'หน่วย',
    currency: 'บาท',
    validFrom: 'เริ่มใช้',
    validUntil: 'หมดอายุ',
    noExpiry: 'ไม่กำหนดวันหมดอายุ',
    note: 'หมายเหตุ',
    notePlaceholder: 'เหตุผลหรือเงื่อนไขที่ตกลง (ไม่บังคับ)',
    save: 'บันทึกราคา',
    saving: 'กำลังบันทึก...',
    cancel: 'ยกเลิก',
    showExpired: 'แสดงราคาที่หมดอายุ',
    hideExpired: 'ซ่อนราคาที่หมดอายุ',
    empty: 'ยังไม่มีราคาเน็ตเฉพาะลูกค้า',
    effectivePrice: 'ราคาที่ระบบใช้ปัจจุบัน',
    updated: 'แก้ล่าสุด',
    statusActive: 'ใช้งาน',
    statusScheduled: 'รอเริ่มใช้',
    statusExpired: 'หมดอายุ',
    statusExpiredActive: 'หมดช่วงเวลา · ต้องปิดกฎ',
    expire: 'หมดอายุทันที',
    expireConfirm: 'ยืนยันหมดอายุ',
    expireQuestion: 'ปิดกฎราคา SKU นี้ และให้ระบบใช้ราคา Tier หรือราคาคลัง',
    invalidProduct: 'กรุณาเลือกสินค้าก่อน',
    invalidPrice: 'ราคาเน็ตต้องมากกว่า 0',
    invalidDates: 'วันหมดอายุต้องอยู่หลังวันเริ่มใช้',
    duplicate: 'SKU นี้มีกฎราคาเน็ตที่ยังเปิดอยู่ กรุณาปิดกฎเดิมก่อนเพิ่มราคาใหม่',
    loadFailed: 'โหลดราคาไม่สำเร็จ',
    saveFailed: 'บันทึกราคาไม่สำเร็จ',
    expiredSaved: 'ปิดราคาเน็ตแล้ว',
    saved: 'บันทึกราคาแล้ว',
    priceBase: 'ราคาปกติ',
    priceTier: 'ราคา Tier',
    priceNet: 'ราคาเน็ตลูกค้า',
    priceCalculated: 'ราคาที่คำนวณ',
  },
} as const;
